### This is the main way to configure the application (other than annotations).
### This file is in Yaml format but you can also configure spring boot using the traditional
### Java properties file format.

spring.jmx:
   enabled: false

spring.datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:gestioncra;MODE=MySQL

server:
  port: 8090

#todo: make sure to always enable security in production
security:
  basic:
    enabled: false


---
spring:
  profiles: test
  h2:
    console:
      enabled: true

spring.jpa:
    #hibernate.ddl-auto: create-drop

hotel.service:
  name: 'test profile:'

logging:
  file: gestion_cra.log
  org.hibernate: INFO